name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.2
  firebase_core: ^2.25.2
  firebase_ui_auth: ^1.12.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  logger: ^2.0.2+1
  riverpod_annotation: ^2.3.3
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.11
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
